### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by AlessandroTolomio** [willowtreeapps/ouroboros#14]
Hi,
I use the carousel for my tvapp. My cells have one image (max 100kb), and 2 labels adjusted with autolayout. During swipe there is a lagging, any ideas?

**Comment by mattyohe** [comment]
@AlessandroTolomio Thanks for reporting this issue, we'll look at tracking this down for you.

Also, if you can throw together a very quick test project that demonstrates what you're seeing, that likely could speed up troubleshooting.

**Comment by AlessandroTolomio** [comment]
Hi @mattyohe! Now I use SDWebImage to load images and the problem seems to be solved.

**Comment by ianterrell** [comment]
Glad you got it solved! 

I'd love to see your usage of this library in your app once you ship. If you feel like sharing please ping me when you launch. :) ian.terrell@willowtreeapps.com
