### ISSUE TITLE
didSelectItemAtIndexPath is never getting called

### ISSUE THREAD

**Issue by mattwelch** [willowtreeapps/ouroboros#19]
In both my project, and the OuroborosExample project, the `didSelectItemAtIndexPath` method is never called when a cell is selected. If I change the collection view to an actual `UICollectionView` (in the instance variable and in the storyboard), the `didSelectItemAtIndexPath` method does get correctly called.

Any idea what may be going wrong?

**Comment by ianterrell** [comment]
Yes. By design and documentation, the `InfiniteCarousel` is its own delegate. To access delegate methods other than what it is using itself, please subclass `InfiniteCarousel` and add your delegate method forwarding there via `rootDelegate`.

**Comment by vijayviswas** [comment]
@ianterrell  - 
I am setting up InfiniteCarousel view programmatically
`
collectionView = [[ASCInfiniteCarousel alloc]initWithFrame:CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, 648) collectionViewLayout:layout];

         [collectionView setDataSource:self];

        [collectionView setDelegate:self];
`

I have subclassed InfiniteCarousel 

`
open class ASCInfiniteCarousel: InfiniteCarousel  {

    /*
    // Only override draw() if you perform custom drawing.
    // An empty implementation adversely affects performance during animation.
    override func draw(_ rect: CGRect) {
        // Drawing code
    }
    */
    func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath){
        
        print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
    }
}`

But still didSelectItemAtIndexPath is not getting called. Am I missing anything here?
@mattwelch

**Comment by ianterrell** [comment]
@vijayviswas From the look of it, your delegate method is on the carousel instance, while you expect the delegate to be on the owner of the carousel. Good luck!

**Comment by nishayadav-shineweb** [comment]
@mattwelch did you get solution for did select  ?

**Comment by nishayadav-shineweb** [comment]
@mattwelch  I'm getting same issue it's never getting called
