### ISSUE TITLE
Include screenshot in readme

### ISSUE THREAD

**Issue by chaseacton** [willowtreeapps/ouroboros#22]
It would be nice to see a screenshot of what this does without having to run `pod try 'WillowTreeOuroboros'`

![simulator screen shot mar 29 2016 7 20 14 pm](https://cloud.githubusercontent.com/assets/3307194/14129904/4af3d62a-f5e3-11e5-9b29-bdbe409632b0.png)

**Comment by mattyohe** [comment]
@chaseacton If you make a PR that includes the above screenshot, I'd happily merge it in in short order. Maybe we should make an animated GIF even...

Anyway, thanks for the feedback!

**Comment by chaseacton** [comment]
Done: https://github.com/willowtreeapps/ouroboros/pull/23
